# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries
name: Release to PyPi

on:
  release:
    types: [created, published]
  workflow_dispatch:
    inputs:
      PACKAGE_VERSION:
        description: "Package Version"
        required: true
        default: "23.23.23rc23"

# TODO: Check why "id-token" doesn't work with PyPi's Truster Publisher
# https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/
permissions:
  id-token: write
  contents: write # To create the tag for workflow_dispatch

run-name: Published ${{ inputs.PACKAGE_VERSION }} by @${{ github.actor }}

env:
  PACKAGE_VERSION: ${{ github.event.inputs.PACKAGE_VERSION }}

jobs:
  publish:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    env:
      RELEASE_REF: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: pip
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - name: Prepare .VENV directory
        run: make venv-prepare
      - name: Install Python dependencies
        run: make venv-install
      - name: Set Release Version - GitHub Release
        if: github.event_name != 'workflow_dispatch'
        run: |
          export PACKAGE_VERSION=${GITHUB_REF_SLUG}
          echo -n $PACKAGE_VERSION > ./version
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
      - name: Set Release Version - Workflow Dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo -n $PACKAGE_VERSION > ./version
      - name: Validate Release Version
        run: make validate-release-version PACKAGE_NAME=${PACKAGE_VERSION}
      - name: Build Package
        run: make build
      - name: Validate Package
        run: make validate-release-package
      - name: Publish to PyPi
        env:
          TWINE_NON_INTERACTIVE: true
          TWINE_USERNAME: ${{ secrets.PYPI_USER_NAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: make publish
      - name: Create tag
        if: github.event_name == 'workflow_dispatch'
        uses: actions/github-script@v7.0.1
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.PACKAGE_VERSION }}',
              sha: context.sha
            })
