# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries
name: Release to PyPi and DockerHub

on:
  release:
    types: [published, edited]

# https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/
permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-22.04
    env:
      RELEASE_REF: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: pip
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - name: Set Release Version
        run: |
          export RELEASE_VERSION=${GITHUB_REF_SLUG}
          echo -n $RELEASE_VERSION > ./version
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
      - name: Validate Release Version
        run: |
          echo $GITHUB_ENV
          bash scripts/version_validation.sh
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build Package
        run: |
          python setup.py sdist bdist_wheel
          twine check ./dist/*
      - name: Publish to PyPi
        env:
          TWINE_NON_INTERACTIVE: true
        run: |
          twine upload ./dist/*
