name: Tests

on:
  push:
    paths-ignore:
      - "README.md"
      - ".github/workflows/release.yml"
      - "scripts/version_validation.sh"
defaults:
  run:
    shell: bash

env:
  AUDACITY_SCRIPTING_LOGGER_LEVEL: debug

jobs:
  tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
      - name: Prepare .VENV directory
        run: make venv-prepare
      - name: Install Python dependencies
        run: make venv-install
      - name: Install in Edit mode
        run: make venv-install-edit
      - name: Install Audacity
        run: choco install -y audacity --version 3.4.2
      - name: Copy audacity.cfg
        run: make audacity-copy-config
      - name: Get APPDATA Directory
        shell: powershell
        id: appdata
        run: |
          # Get the APPDATA environment variable
          $appData = "APPDATA=" + $Env:APPDATA

          # Get the GITHUB_OUTPUT file path
          $githubOutputFilePath = $Env:GITHUB_OUTPUT

          # Append APPDATA to the file specified by GITHUB_OUTPUT
          Add-Content -Path $githubOutputFilePath -Value $appData
      - name: Start Audacity and Run Tests
        env:
          APPDATA: ${{ steps.appdata.outputs.APPDATA }}
          AUDACITY_PREFERENCES_PATH: ${{ steps.appdata.outputs.APPDATA }}\\audacity\\audacity.cfg
        run: |
          echo "APPDATA = ${APPDATA}"
          echo "AUDACITY_PREFERENCES_PATH = ${AUDACITY_PREFERENCES_PATH}"
          cat "$AUDACITY_PREFERENCES_PATH"
          make audacity-start && \
          make venv-test
