name: Tests

on:
  push:
    paths-ignore:
      - "README.md"
      - ".github/workflows/release.yml"
      - "scripts/version_validation.sh"
defaults:
  run:
    shell: bash

env:
  AUDACITY_SCRIPTING_LOGGER_LEVEL: info

jobs:
  tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
      - name: Prepare .VENV directory
        run: make venv-prepare
      - name: Install Python dependencies
        run: make venv-install
      - name: Install in Edit mode
        run: make venv-install-edit
      - name: Install Audacity
        run: choco install -y audacity --version 3.4.2 1>/dev/null
      # - name: Get APPDATA Directory
      #   shell: powershell
      #   id: appdata
      #   run: |
      #     $appData = "APPDATA=" + $Env:APPDATA
      #     print($appData)
      #     $githubEnvPath = $Env:GITHUB_ENV
      #     print($githubEnvPath)
      #     Add-Content -Path $githubEnvPath -Value $appData
      #     $audacityPreferencesPath = "AUDACITY_PREFERENCES_PATH=" + $Env:APPDATA + "\audacity\audacity.cfg"
      #     Add-Content -Path $githubEnvPath -Value $audacityPreferencesPath
      - name: Start Audacity for the first time
        run: make audacity-start
      - name: Kill Audacity
        run: make audacity-kill
      - name: Update audacity.cfg
        run: make audacity-update-config
      - name: Re-Start Audacity and Run Tests
        run: |
          make print-vars
          make audacity-start && \
          make venv-test
