name: Tests

on:
  push:
    paths-ignore:
      - "README.md"
      - ".github/workflows/release.yml"
      - "scripts/version_validation.sh"
defaults:
  run:
    shell: bash

env:
  AUDACITY_SCRIPTING_LOGGER_LEVEL: info

jobs:
  tests:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
      - name: Prepare .VENV directory
        run: make venv-prepare
      - name: Install Python dependencies
        run: make venv-install PACKAGE_NAME=pywin32
      - name: Install in Edit mode
        run: make venv-install-edit
      - name: Install Tests Requirements
        run: |
          # choco install -y audacity --version 3.4.2
          make audacity-download && \
          make audacity-install && \
          choco install -y pipelist
      - name: Start Audacity for the first time
        run: make audacity-start
      - name: Kill Audacity
        run: make audacity-kill
      - name: Update audacity.cfg
        run: make audacity-update-config
      - name: Prepare for test
        run: make wrapper-prepare-test
      - name: Print vars and configurations before running tests
        run: |
          make print-vars
          make audacity-print-config
      - name: Test Audacity Pipe
        run: make audacity-test-pipe
      - name: Run Unit Tests
        run: make venv-test-unittests
      - name: Prepare for test
        run: make wrapper-prepare-test
      - name: Run CLI Tests
        run: make venv-test-cli
