name: Tests

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "README.md"
      - ".github/workflows/release.yml"
      - "scripts/version_validation.sh"
defaults:
  run:
    shell: bash

env:
  AUDACITY_SCRIPTING_LOGGER_LEVEL: info

jobs:
  tests:
    name: Tests
    timeout-minutes: 10
    strategy:
      matrix:
        include:
          - OS: windows-2022
          - OS: macos-12
          - OS: ubuntu-22.04
    runs-on: ${{ matrix.OS }}
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
      - name: Prepare .VENV directory
        run: make venv-prepare
      - name: Install Python dependencies
        run: make venv-install
      - name: Install in Edit mode
        run: make venv-install-edit
      - name: Download Audacity
        if: matrix.OS == 'windows-2022' || matrix.OS == 'ubuntu-22.04'
        run: make audacity-download
      - name: Install Linux Requirements
        if: matrix.OS == 'ubuntu-22.04'
        run: |
          sudo add-apt-repository universe && \
          sudo apt-get update && \
          sudo apt-get install -y xclip libfuse2 libgtk2.0 libasound2 libjack-jackd2-0 libportaudio2
      - name: Install Audacity
        run: make audacity-install
      - name: Start Audacity for the first time
        run: make audacity-start
      - name: Kill Audacity
        run: make audacity-kill
      - name: Update audacity.cfg
        run: make audacity-update-config
      - name: Prepare for test
        run: make wrapper-prepare-test
      - name: Print vars and configurations before running tests
        run: |
          make print-vars
          make audacity-print-config
      - name: Run Unit Tests
        run: make venv-test-unittests
      - name: Prepare for test
        run: make wrapper-prepare-test
      - name: Run CLI Tests
        run: make venv-test-cli
